#!/bin/bash

echo "=== Clearing Browser Cookies for EC2 Instance ==="
echo "URL: http://15.134.207.129:3001"
echo ""
echo "Manual steps to clear cookies:"
echo "1. Open Firefox/Chrome"
echo "2. Press F12 to open DevTools"
echo "3. Go to Application/Storage tab"
echo "4. Click on Cookies → http://15.134.207.129"
echo "5. Click 'Clear All' or select individual cookies to delete"
echo "6. Refresh the page and try login again"
echo ""
echo "Or use these keyboard shortcuts:"
echo "Firefox: Ctrl+Shift+Delete → Clear cookies for 15.134.207.129"
echo "Chrome: Ctrl+Shift+Delete → Clear cookies for 15.134.207.129"
echo ""
echo "After clearing cookies:"
echo "1. Make sure AWS Cognito app client has 'Require HTTPS' unchecked"
echo "2. Wait 5-10 minutes for AWS changes to propagate"
echo "3. Try logging in again"
